### ISSUE TITLE
[Packaging] Let's publish a conda package with conda-forge

### ISSUE THREAD

**Issue by pietakio** [mathandy/svgpathtools#152]
For ease of use, it'd be *wondrous* if `svgpathtools` also published [(Ana|Mini)conda](https://docs.conda.io/en/latest/miniconda.html)-compatible conda packages via [conda-forge, a third-party open-source community-maintained conda channel hosting basically everything](https://conda-forge.org). Conda-forge is roughly analogous to the [PyPI cheeseshop](https://pypi.org) in terms of popularity and usability, while being considerably more:

* **General-purpose,** because conda packages multiple languages (e.g., Julia, Python, R) rather than merely Python.
* **Binary-friendly,** because conda also packages low-level binary dependencies (typically authored in C or C++) often required as mandatory runtime dependencies by Python packages. Classic examples include CUDA, OpenCASCADE, MKL, and VTK. Although binary dependencies can *sometimes* be packaged as `pip`-friendly wheels, doing so is [complicated by justifiable bandwidth and filesize constraints on PyPI](https://discuss.python.org/t/what-to-do-about-gpus-and-the-built-distributions-that-support-them/7125).
* **Science-friendly,** because most scientific Python packages are packaged first for conda and only second for PyPI. Our go-to example here is [CadQuery, a popular Python package for procedural CAD and CAE **only installable with conda**](https://cadquery.readthedocs.io/en/latest/installation.html) that [currently provides no PyPI packages despite having previously done so](https://github.com/CadQuery/cadquery/issues/153).

In our case, our downstream project requires both CadQuery *and* svgpathtools — the former only installable with `conda` and the latter only installable with `pip`. Not a good place to be!

Our team maintains a [pure-Python open-source package](https://github.com/beartype/beartype) concurrently packaged to both [PyPI](https://pypi.org/project/beartype) and [conda-forge](https://anaconda.org/conda-forge/beartype). So, we can personally attest that conda-forge trivializes Python packaging. Whenever you bump your PyPI release, *amazing* conda-forge automation will [automatically bump your conda-forge release to keep the two in sync with no manual labour required](https://conda-forge.org/docs/maintainer/updating_pkgs.html#pushing-to-regro-cf-autotick-bot-branch).

Thanks again for all the SVG path tools, all! This project continues to impress and wow us. :heart_eyes:

**Comment by mathandy** [comment]
Hi @pietakio and @leycec, I'm a long time user of conda.  In my experience pip and conda work well together.  If svgpathtools had a conda package, what would that enable you to do that you can't do now?

**Comment by leycec** [comment]
**Sure!** Off the top of my balding head:

* **Reproduceable deep constraints resolution** against non-Python dependencies – which, since `svgpathtools` requires NumPy, `svgpathtools` transitively requires. Stuff like BLAS, MKL, and LAPACK.
* **Eliminating multiple critical points of failure** from our deployment stack (e.g., PyPA, PyPI, `pip` itself) that have hit our team elsewhere in the past. The smaller our build-time dependency tree, the less likely our deployments are to explode in our servers' faces.

`svgpathtools` is our last PyPI-only mandatory dependency. Since NumPy and `svgwrite` both have well-maintained `conda-forge` packages *and* since `svgpathtools` is pure-Python, packaging `svgpathtools` via `conda-forge` should take no more than a few minutes at most.

If you still have valid concerns about packaging `svgpathtools` via `conda-forge`, that's totally understandable. We're not here to step on anyone's feet or ignite an acrimonious debate about the relative merits of `conda` versus `pip`; they both have their merits in different contexts. We kinda just need one rather than the other at the moment. :wink: 

Thanks for all the generous attention and continued volunteerism, Andy! You're awesome and so is `svgpathtools`.

**Comment by mathandy** [comment]
Well I tried, but the I don't think anything usable got uploaded -- the builds seem to think there are more requirements to `svgpathtools` than there are.  How come you folks want me to do this -- I think you can do it yourself, can't you?

**Comment by mathandy** [comment]
E.g. svgpathtools has nothing to do with CUDA, but ...
![image](https://user-images.githubusercontent.com/3175485/123536215-d71c3a80-d6dd-11eb-81fe-82e8bffe4784.png)

**Comment by leycec** [comment]
It is sad. No worries! We'll solve this for all involved. We thought you might like to have full authoritative control over packaging `svgpathtools`. In hindsight, ain't nobody got that kinda free volunteer time, right?

It looks like you might have been trying to build a `conda` recipe without using `conda-forge` automation, maybe? In any case, I'll submit a new `conda-forge` recipe for `svgpathtools` and add you as co-maintainer. Apologies for all the packaging woes, @mathandy. :sob:

**Comment by leycec** [comment]
**Hmm...** It looks like `svgpathtools` has [one failing test on Windows](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=343279&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=23010c01-6a9d-5f94-9037-792618644b77&l=868):

```
.................F......................................................
======================================================================
FAIL: test_point_to_t (test_path.ArcTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda\conda-bld\svgpathtools_1624827965439\test_tmp\test\test_path.py", line 659, in test_point_to_t
    self.assertAlmostEqual(orig_t, computed_t, msg="arc %s at t=%f is point %s, but got %f back" % (a, orig_t, p, computed_t))
AssertionError: 0.4873706102697135 != 0.48737054659373674 within 7 places (6.367597676915082e-08 difference) : arc Arc(start=(931.141074443372+536.3734513599887j), radius=(738.0437682468166+4598.318237538378j), rotation=0.0, large_arc=False, sweep=True, end=(-543.784762354835+171.57798414651836j)) at t=0.487371 is point (193.67800869282425+4952.293895458512j), but got 0.487371 back

----------------------------------------------------------------------
```

We can't reasonably resolve from the `conda` side, so we'll just ignore tests on Windows for now. To investigate this further, you'll probably want to either add an [Appveyor CI configuration](https://www.appveyor.com) (e.g., `.appveyor.yml`) *or* transition from Travis-CI to [GitHub Actions](https://github.com/features/actions) (e.g., `.github/workflows/`), which transparently supports both Linux and Windows. Travis-CI only supports the former.

*Anyway.* `conda` packaging is basically *fait accompli* at this point, so that's great! Let's see if we can seal the deal with `conda-forge` tests now. :handshake:

**Comment by leycec** [comment]
The deal has been sealed! [`svgpathtools` is now directly installable and updatable with `conda`](https://anaconda.org/conda-forge/svgpathtools). You're probably *excrutiatingly* busy, but it'd be swell if you could add this snippet to [your **Setup** instructions](https://github.com/mathandy/svgpathtools#setup) when you find a free moment:

```
conda install -c conda-forge svgpathtools 
```

Thanks for everything! This can now be safely closed. Oh, and you [might want to take a look at that failing Windows test](https://github.com/mathandy/svgpathtools/issues/152#issuecomment-869239326) – or not, you know. Have a great (and hopefully not *too* hot) summer. :desert:

**Comment by mathandy** [comment]
Thanks for the conda work @leycec!

The test fail I'd guess was caused by an old choice to randomly generate certain tests -- from the look of it, it's just floating point error.
I lowered the tolerance on all `assertAlmostEqual` tests in the `test_path` module that were using the `unittest` default tolerance.  I think that'll make errors like the one you encountered much less likely.
